server:
  port: 8081

api:
  key: ${API_KEY}

spring:
  application:
    name: service-metrics-service
  datasource:
    url: ${PG_URL}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

kafka:
  consumer:
    auto-offset-reset: earliest
